version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  redis:
    image: redis/redis-stack:latest
    hostname: redis
    ports:
      - "6379:6379"
      - "8001:8001"
  go_security:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - .:/go-security
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis